import React from "react"; // Import React library
import { Inter } from "next/font/google"; // Import Inter font from Google Fonts
import "./globals.css";
import Navbar from "@/app/Navbar/navbar"; // Import global CSS styles

// Define Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the page
export const metadata = {
  title: "Create Next App", // Title of the page
  description: "Generated by create next app", // Description of the page
};

// RootLayout component definition
const RootLayout = ({ children }) => {
  return (
      // HTML structure for the layout
      <html lang="en">
      <head>
        <meta charSet="UTF-8" /> {/* Character set meta tag */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {/* Viewport meta tag */}
        <title>{metadata.title}</title> {/* Title of the page */}
      </head>
      <body className={inter.className}> {/* Apply Inter font class */}
      <Navbar/>
      <main>
        <div>{children}</div> {/* Render children components */}
      </main>
      </body>
      </html>
  );
};

export default RootLayout; // Export RootLayout component as default